-- init DB SYSTEM_USER_INFO
INSERT INTO SYSTEM_USER_INFO (ACCOUNT, PASSWORD, USER_NAME, PHONE, ADDRESS)
VALUES ('Desktop' ,'0000','爹斯克','11055678','台灣');
INSERT INTO SYSTEM_USER_INFO (ACCOUNT, PASSWORD, USER_NAME, PHONE, ADDRESS)
VALUES ('Enoxs' ,'0000','伊諾','11055678','台灣');
INSERT INTO SYSTEM_USER_INFO (ACCOUNT, PASSWORD, USER_NAME, PHONE, ADDRESS)
VALUES ('RHZ' ,'0204','R星','11055678','台灣');

-- init DB BOOK_MSG
INSERT INTO BOOK_MSG (ID, NAME, AUTHOR, PUBLICATION_DATE, PUBLICATION, PRICE, IMAGE, REMARK) VALUES
('1','好策略‧壞策略：第一本讓歐洲首席經濟學家欲罷不能、愛不釋手的策略書','魯梅特 (Richard P. Rumelt)','2018-10-09','天下文化 ','356','GoodStrategy.jpeg','REMARK#1');
INSERT INTO BOOK_MSG (ID, NAME, AUTHOR, PUBLICATION_DATE, PUBLICATION, PRICE, IMAGE, REMARK) VALUES
('2','華杉講透《孫子兵法》','華杉','2017-09-18','印刻 ','394','TheArtOfWar.jpeg','REMARK#2');
INSERT INTO BOOK_MSG (ID, NAME, AUTHOR, PUBLICATION_DATE, PUBLICATION, PRICE, IMAGE, REMARK) VALUES
('3','無瑕的程式碼：整潔的軟體設計與架構篇','Robert C. Martin','2018-05-16','博碩 ','458','CleanCodeArchitecture.jpeg','REMARK#3');
INSERT INTO BOOK_MSG (ID, NAME, AUTHOR, PUBLICATION_DATE, PUBLICATION, PRICE, IMAGE, REMARK) VALUES
('4','高績效心智：全新聰明工作學，讓你成為最厲害的1%','莫頓‧韓森(Morten T. Hansen)','2018-05-31','天下文化 ','356','GreatAtWork.jpeg','REMARK#4');
INSERT INTO BOOK_MSG (ID, NAME, AUTHOR, PUBLICATION_DATE, PUBLICATION, PRICE, IMAGE, REMARK) VALUES
('5','精準預測：如何從巨量雜訊中，看出重要的訊息？','奈特．席佛 (Nate Silver)','2013-09-06','三采','450','TheSignalAndThe Noise.jpeg','REMARK#5');




